### ISSUE TITLE
Support component that does not import React but that still have props

### ISSUE THREAD

**Issue by MoOx** [brigand/babel-plugin-flow-react-proptypes#14]
I have a component that does not import React at all (not required)

```js
// @flow
import { Component } from "react"

type Props = {
  initialState?: State,
  children: (
    state: State,
    setState: (state: State) => void,
  ) => ReactElement,
}

type State = {
  [key: string]: any,
}

export default class Playground extends Component<void, Props, State> {

  state: State;

  constructor(props: Props) {
    super(props)
    this.state = (typeof props.initialState === "object")
      ? props.initialState
      : {}
  }

  handleStateChange(state: State) {
    this.setState(state)
  }

  render(): ReactElement {
    return (
      this.props.children(
        this.state,
        (state) => this.handleStateChange(state),
      )
    )
  }
}
```

When I use this component, I got a "React is not defined" error. I suspect that babel-plugin-flow-react-proptypes replace the Props by `React.PropTypes` even if React is not in the current scope.

**Comment by brigand** [comment]
I think this is so rare that it's not worth solving. The only time this happens is when you have a component that doesn't use jsx/React.createElement. JSX is similar in that it requires React to be in scope.

**Comment by MoOx** [comment]
Currently this throw an error and I took me a while to solve, but you decide. I am not currently comfortable enough with babel plugin authoring to fix this myself.

**Comment by MoOx** [comment]
You could also just add by default `import { PropTypes } from "react"` and use `PropTypes` directly.

**Comment by ericwooley** [comment]
I think this is related: 

I am getting a runtime error about react not being defined in a file unrelated to where React components or any props declarations.
```js
/* @flow */
// ------------------------------------
// Constants
// ------------------------------------
export const SET_TOKEN = 'SET_TOKEN'
export const CLEAR_TOKEN = 'CLEAR_TOKEN'
// ------------------------------------
// Actions
// ------------------------------------
export const setToken = (token: string): Action => ({
  type: SET_TOKEN,
  payload: `Token ${token}`
})

export const clearToken = (): Action => ({
  type: CLEAR_TOKEN
})

// ERROR HERE about React not being defined.
// Adding type object solves the problem.
export const actions = {
  setToken,
  clearToken
}

// ------------------------------------
// Action Handlers
// ------------------------------------
export type HeadersState = {Authorization: string}

const initialState: HeadersState = JSON.parse(localStorage.getItem('headers') || 'false') ||
  {Authorization: null}
const ACTION_HANDLERS = {
  [SET_TOKEN]: (state: HeadersState, action): HeadersState => {
    const newState = {
      ...state,
      Authorization: action.payload
    }
    localStorage.setItem('headers', JSON.stringify(newState))
    return newState
  },
  [CLEAR_TOKEN]: (state: HeadersState) => ({...state, Authorization: null})
}

// ------------------------------------
// Reducer
// ------------------------------------

export default function authReducer (state: HeadersState = initialState, action: Action): HeadersState {
  const handler = ACTION_HANDLERS[action.type]
  return handler ? handler(state, action) : state
}
```

**Comment by brigand** [comment]
@ericwooley thanks for the report.

I think the solution here is to generate `require('react').propTypes.string` instead of `React.propTypes.string`.

The downside is that it won't work outside of common.js environments, but I think that's an acceptable tradeoff.

**Comment by ericwooley** [comment]
@brigand 

I am trying to do this, then PR, but I have no idea where to find that. Any pointers on where to start?

**Comment by brigand** [comment]
I think I already fixed it. Pushed as 0.5.0.

**Comment by ericwooley** [comment]
@brigand Still having the same error, `Uncaught ReferenceError: React is not defined` :(

**Comment by brigand** [comment]
Okay, I think I got it now. 0.5.1. @ericwooley let me know if it works now.

**Comment by ericwooley** [comment]
@brigand I appreciate the effort! But it still has the same problem :(

**Comment by brigand** [comment]
Are you running it on the same code? I get this output. There are no references to React in it.

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _ACTION_HANDLERS;

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

exports.default = authReducer;

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

// ------------------------------------
// Constants
// ------------------------------------
var SET_TOKEN = exports.SET_TOKEN = 'SET_TOKEN';
var CLEAR_TOKEN = exports.CLEAR_TOKEN = 'CLEAR_TOKEN';
// ------------------------------------
// Actions
// ------------------------------------
var setToken = exports.setToken = function setToken(token) {
  return {
    type: SET_TOKEN,
    payload: 'Token ' + token
  };
};

var clearToken = exports.clearToken = function clearToken() {
  return {
    type: CLEAR_TOKEN
  };
};

// ERROR HERE about React not being defined.
// Adding type object solves the problem.
var actions = exports.actions = {
  setToken: setToken,
  clearToken: clearToken
};

// ------------------------------------
// Action Handlers
// ------------------------------------
Object.defineProperty(module.exports, 'babelPluginFlowReactPropTypes_proptype_HeadersState', require('react').PropTypes.shape({
  Authorization: require('react').PropTypes.string.isRequired
}));


var initialState = JSON.parse(localStorage.getItem('headers') || 'false') || { Authorization: null };
var ACTION_HANDLERS = (_ACTION_HANDLERS = {}, _defineProperty(_ACTION_HANDLERS, SET_TOKEN, function (state, action) {
  var newState = _extends({}, state, {
    Authorization: action.payload
  });
  localStorage.setItem('headers', JSON.stringify(newState));
  return newState;
}), _defineProperty(_ACTION_HANDLERS, CLEAR_TOKEN, function (state) {
  return _extends({}, state, { Authorization: null });
}), _ACTION_HANDLERS);

// ------------------------------------
// Reducer
// ------------------------------------

function authReducer() {
  var state = arguments.length <= 0 || arguments[0] === undefined ? initialState : arguments[0];
  var action = arguments[1];

  var handler = ACTION_HANDLERS[action.type];
  return handler ? handler(state, action) : state;
}
```

**Comment by ericwooley** [comment]
@brigand 

> ~~~@brigand I appreciate the effort! But it still has the same problem ~~~
> I figured it out! Sorry, I had the plugins in the wrong order. DOH.
> 
> You are the man. You have a bitcoin address?


I ninja edited my last comment. Figured you wouldn't be on in time to notice.

**Comment by brigand** [comment]
Great! I don't, but feel free to send something on paypal at f.bagnardi@gmail.com

**Comment by brettstack** [comment]
@MoOx it looks like you have some solution for defining `children` - can you comment over at #48? What does your `ReactElement` type look like?
