### ISSUE TITLE
Wrong accessNode.name on imported type

### ISSUE THREAD

**Issue by kubijo** [brigand/babel-plugin-flow-react-proptypes#172]
Hi.

I'm trying to hunt down a bug where some of my prop-types are **generated for the wrong exported flow type**.

When I **inline the type definition** to the component's file, the **error goes away**.

## To illustrate this consider following example:

**a.js**
```js
export type MaskDef = Object
export type TextShape = string;
```

**b.js**
```js
import type { MaskDef, TextShape } from './a';
type Props = {
    mask: MaskDef,
    text?: TextShape,
};
// … component code
```

ouput of logging `importedTypes` in [here](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/7b53754f7998530bd0309c2aee90cafdc97de1ce/src/index.js#L604) gives me following snippet

```js
{
    MaskDef: {
        exportName: 'bpfrpt_proptype_MaskDef',
        accessNode: {
            type: 'Identifier',
            name: 'bpfrpt_proptype_MaskDef'
        }
    },
    TextShape: {
        exportName: 'bpfrpt_proptype_TextShape',
        accessNode: {
            type: 'Identifier',
            name: 'bpfrpt_proptype_MaskDef'
        }
    }
}
```

As you can see, the accessNode name is wrong for the second flow type.

Considering how involved this code has got and that I'm approaching it with a blank slate, I'm pretty much at loss.
It'd great then if you could help with debugging this or if you'd have at least some hunches for the source of such error

**Comment by brigand** [comment]
Thanks for the report! Fixed in 15.0.0. It'll now output

```js
const C = props => React.createElement('div', null);
C.propTypes = {
    mask: function () {
        return (typeof bpfrpt_proptype_MaskDef === 'function' ? bpfrpt_proptype_MaskDef.isRequired ? bpfrpt_proptype_MaskDef.isRequired : bpfrpt_proptype_MaskDef : PropTypes.shape(bpfrpt_proptype_MaskDef).isRequired).apply(this, arguments);
    },
    text: function () {
        return (typeof bpfrpt_proptype_TextShape === 'function' ? bpfrpt_proptype_TextShape : PropTypes.shape(bpfrpt_proptype_TextShape)).apply(this, arguments);
    }
};
import { bpfrpt_proptype_MaskDef } from './a';
import { bpfrpt_proptype_TextShape } from './a';
import PropTypes from 'prop-types';
```

Room for improvement in not duplicating the import declarations, but it seems to be working correctly.

Also fixed some mistakes in the test output we didn't catch previously.

**Comment by kubijo** [comment]
Man, that was fast ... however I'm still having the same issues with the production code so currently I'm trying to replicated the previous test to see if I'm doing something wrong elsewhere

**Comment by brigand** [comment]
@kubijo to experiment with it, in this repo you can create e.g. a.js in the root, and then run `./scripts/runOnFile a.js --leave-esm`.

**Comment by kubijo** [comment]
Never mind, it was an error between display & chair (code was not recompiled).

Hats of for your aptly response sir!
