### ISSUE TITLE
Support annotating React functional components

### ISSUE THREAD

**Issue by Rovack** [brigand/babel-plugin-flow-react-proptypes#55]
Currently, there are several edge cases where the plugin fails to recognize React stateless functional components. See [this](https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/54) issue for some examples.

While automatically recognizing them in all possible edge cases might be very difficult (would require actual type analysis), offering a way for the developer to manually annotate the functions might suffice for most real-world scenarios.

Basing this on Flow type annotations indicating the function returns JSX, or perhaps a `ReactElement`, should do the trick.

**Example:**
```
const MyComponent = (props : Props) : ReactElement<*> => {
  const component = someComplicatedPathThatEventuallyReturnsJSX();
  return component;
};
```
Because of `someComplicatedPathThatEventuallyReturnsJSX`, it might not be possible for the plugin to realize this function is a React component, but since it's explicitly annotated as such (with Flow hopefully doing all the type analysis to make sure this is true), the plugin should just see this as a React component and generate propTypes accordingly.

**Comment by brigand** [comment]
Should be fixed in 0.17.0. Let me know if it works for you.

**Comment by Rovack** [comment]
Yeah, seems to work perfectly. :)

It still doesn't work with jest code coverage for some reason, but I think at that point it might be more of an Istanbul issue than an issue with this plugin.

Thanks!
