### ISSUE TITLE
React.PropTypes are deprecated.  Need to add 'prop-types' library

### ISSUE THREAD

**Issue by harsimranb** [brigand/babel-plugin-flow-react-proptypes#78]
I will try to look into this when I have a chance.

**Comment by brigand** [comment]
@harsimranb this was already addressed, are you having issues on >=1.0.0?

Ref: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/72

**Comment by harsimranb** [comment]
Yes, this has been resolved.  It was another library complaining, I misread the error.  Thanks for confirming!

**Comment by EnoahNetzach** [comment]
@brigand isn't `require('react').PropTypes` still present in `index.js` [here](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/v2.1.1/src/index.js#L244) and [here](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/v2.1.1/src/index.js#L311)?

**Comment by brigand** [comment]
@EnoahNetzach thanks for pointing that out. I'll fix it.

**Comment by EnoahNetzach** [comment]
I just did a PR (#81). I'm updating the tests right now ^_^
